name: 'portfolio_dbt'
version: '1.0.0'

profile: 'portfolio_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  portfolio_dbt:
    +materialized: table
    staging:
      +materialized: view
    marts:
      +materialized: table