portfolio_dbt:
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('SUPABASE_HOST', 'localhost') }}"
      user: postgres
      password: "{{ env_var('SUPABASE_PASSWORD', 'password') }}"
      port: 5432
      dbname: postgres
      schema: dbt_dev
      threads: 1
      keepalives_idle: 0
  target: dev